
import { ai } from "./client";

export async function generateImage(prompt: string, aspectRatio: string, imageStyle: string, negativePrompt: string): Promise<string> {
    const styleKeywords: Record<string, string> = {
        'Minimalist & Clean': ', minimalist, clean aesthetic, simple',
        'Lush & Organic': ', lush, organic, natural, botanical',
        'Luxury & Gold': ', luxury, elegant, gold accents, rich textures',
        'Vibrant & Playful': ', vibrant colors, playful, pop art style',
    };
    
    let finalPrompt = `${prompt}, for Pakistani skincare brand Chamkili, product photography, high resolution, photorealistic, aesthetic`;
    finalPrompt += styleKeywords[imageStyle] || '';
    if (negativePrompt) finalPrompt += `. Avoid: ${negativePrompt}.`;

    const response = await ai.models.generateImages({
        model: 'imagen-3.0-generate-002',
        prompt: finalPrompt,
        config: { numberOfImages: 1, outputMimeType: 'image/jpeg', aspectRatio },
    });

    if (response.generatedImages?.[0]?.image.imageBytes) {
        return `data:image/jpeg;base64,${response.generatedImages[0].image.imageBytes}`;
    }
    throw new Error("No image was generated by the API.");
}
